import Foundation

public extension AppReport {
    /// Render the full report as GitHub-flavoured Markdown — suitable for
    /// committing as an example, attaching to an issue, or reading in any viewer.
    func markdown() -> String {
        var md = MarkdownBuilder()

        md.h1("App X-Ray — \(name)")
        md.line("> \(summary)")
        md.blank()

        // Identity
        md.h2("Identity")
        md.table(rows: [
            ("Bundle ID", bundleID ?? "—"),
            ("Version", version ?? "—"),
            ("Minimum macOS", minimumOS ?? "—"),
            ("Architectures", architectures.isEmpty ? "—" : architectures.joined(separator: ", ")),
            ("Path", "`\(bundlePath)`")
        ])

        // Badges
        md.h2("Capabilities at a glance")
        for badge in badges {
            let mark = badge.isOn ? "✅" : "⬜️"
            md.bullet("\(mark) \(badge.label)\(badge.isOn && badge.risk >= .notable ? " — \(badge.risk.rawValue)" : "")")
        }
        md.blank()

        // Signature
        md.h2("Code signature")
        md.table(rows: [
            ("Signing", signingKindLabel),
            ("Team ID", signature.teamID ?? "—"),
            ("Identifier", signature.signingIdentifier ?? "—"),
            ("Hardened Runtime", signature.hardenedRuntime ? "yes" : "no"),
            ("Debuggable (get-task-allow)", signature.isDebuggable ? "yes" : "no"),
            ("Sandboxed", isSandboxed ? "yes" : "no"),
            ("Notarized", isNotarized ? "yes" : "no"),
            ("Gatekeeper accepts", gatekeeperAccepted ? "yes" : "no")
        ])
        if !signature.authorities.isEmpty {
            md.line("**Authority chain:** " + signature.authorities.joined(separator: " → "))
            md.blank()
        }

        // Warnings
        if !warnings.isEmpty {
            md.h2("Warnings")
            for w in warnings {
                md.bullet("\(riskIcon(w.risk)) **\(w.title)** — \(w.detail)")
            }
            md.blank()
        }

        // Entitlements
        if !entitlements.isEmpty {
            md.h2("Entitlements (\(entitlements.count))")
            md.tableHeader(["Entitlement", "Value", "Risk", "What it means"])
            for e in entitlements {
                md.tableRow([e.title, "`\(e.valueDescription)`", e.risk.rawValue, e.explanation])
            }
            md.blank()
        }

        // Privacy usage
        if !privacyUsage.isEmpty {
            md.h2("Privacy resources the app can request")
            for p in privacyUsage {
                let reason = p.statedReason.isEmpty ? "_(no reason given)_" : p.statedReason
                md.bullet("**\(p.resource)** — \(reason)")
            }
            md.blank()
        }

        // Private frameworks
        if !privateFrameworks.isEmpty {
            md.h2("Private / undocumented frameworks")
            md.line("_Linking these signals use of undocumented APIs._")
            for p in privateFrameworks { md.bullet("`\(p)`") }
            md.blank()
        }

        // Nested components
        if !nestedComponents.isEmpty {
            md.h2("Nested components (\(nestedComponents.count))")
            md.tableHeader(["Kind", "Path", "Signature", "Sandboxed"])
            for c in nestedComponents {
                let sb = c.sandboxed.map { $0 ? "yes" : "no" } ?? "—"
                md.tableRow([c.kind, "`\(c.path)`", c.signingSummary, sb])
            }
            md.blank()
        }

        // URL schemes & associated domains
        if !urlSchemes.isEmpty {
            md.h2("URL schemes")
            md.line(urlSchemes.map { "`\($0)://`" }.joined(separator: ", "))
            md.blank()
        }
        if !associatedDomains.isEmpty {
            md.h2("Associated domains")
            for d in associatedDomains { md.bullet("`\(d)`") }
            md.blank()
        }

        // Network hints
        if !networkHints.isEmpty {
            md.h2("Network hints (heuristic)")
            md.line("> ⚠️ Extracted statically from strings in the binary. **Not proof of any connection** — only a hint at possible endpoints.")
            for h in networkHints { md.bullet("`\(h)`") }
            md.blank()
        }

        md.blank()
        md.line("---")
        md.line("_Generated by [App X-Ray](https://github.com/) — a local, offline static auditor. App X-Ray reports what an app **can** do, not what it **does**._")

        return md.text
    }

    // MARK: - Labels

    private var signingKindLabel: String {
        switch signature.kind {
        case .developerID: return "Developer ID"
        case .appleDevelopment: return "Apple Development"
        case .appleSystem: return "Apple system software"
        case .adhoc: return "Ad-hoc (no identity)"
        case .unsigned: return "Unsigned"
        case .other: return "Other"
        }
    }

    private func riskIcon(_ risk: RiskLevel) -> String {
        switch risk {
        case .info: return "ℹ️"
        case .notable: return "⚠️"
        case .high: return "🔴"
        }
    }
}

/// A tiny helper that accumulates Markdown without littering call sites with
/// string interpolation and newline bookkeeping.
private struct MarkdownBuilder {
    private(set) var text = ""

    mutating func h1(_ s: String) { text += "# \(s)\n\n" }
    mutating func h2(_ s: String) { text += "## \(s)\n\n" }
    mutating func line(_ s: String) { text += "\(s)\n" }
    mutating func bullet(_ s: String) { text += "- \(s)\n" }
    mutating func blank() { text += "\n" }

    mutating func table(rows: [(String, String)]) {
        text += "| Field | Value |\n|---|---|\n"
        for (k, v) in rows { text += "| \(k) | \(escape(v)) |\n" }
        text += "\n"
    }

    mutating func tableHeader(_ columns: [String]) {
        text += "| " + columns.joined(separator: " | ") + " |\n"
        text += "|" + columns.map { _ in "---" }.joined(separator: "|") + "|\n"
    }

    mutating func tableRow(_ cells: [String]) {
        text += "| " + cells.map { escape($0) }.joined(separator: " | ") + " |\n"
    }

    private func escape(_ s: String) -> String {
        s.replacingOccurrences(of: "|", with: "\\|").replacingOccurrences(of: "\n", with: " ")
    }
}
